org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
gradle.cache.push=false

mod_name=Upgrade Aquatic
mod_id=upgrade_aquatic
mod_version=7.0.0
mc_version=1.21.1

neoforge=21.1.129
parchment=2024.11.17
blueprint=8.0.4-beta1
jei=19.21.0.247

boatload=6.0.0
clayworks=4.0.0
gallery=2.0.0
woodworks=4.0.1-beta1