modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/team-abnormals/upgrade-aquatic/issues"
license = "https://github.com/team-abnormals/upgrade-aquatic/blob/main/LICENSE.txt"

[[mixins]]
    config = "upgrade_aquatic.mixins.json"

[[mods]]
    modId = "upgrade_aquatic"
    version = "${mod_version}"
    logoFile = "logo.png"
    itemIcon = "upgrade_aquatic:pike"
    configBackground = "upgrade_aquatic:textures/block/coralstone.png"
    authors = "Team Abnormals"
    credits = "SmellyModder, bageldotjpg, Cameron, five, Endergized, PricelessKoala"
    displayURL = "https://www.teamabnormals.com/mods/upgrade-aquatic"
    displayName = "Upgrade Aquatic"
    description = '''
    Expands upon Update Aquatic and aquatic life as a whole with new enemies, sea creatures, and building blocks.
    '''

[[dependencies.upgrade_aquatic]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${mc_version}]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.upgrade_aquatic]]
    modId = "neoforge"
    type = "required"
    versionRange = "[[${neoforge},)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.upgrade_aquatic]]
    modId = "blueprint"
    type = "required"
    versionRange = "[${blueprint},)"
    ordering = "AFTER"
    side = "BOTH"